num_clients: 1


num_clients_list: 
name: edit
attack_window: [20,40]
attack_mode: random # fix-frequency

train:
  mode: blackbox #blackbox, pgd, neurotoxin

  pgd_eps: 1.0
  pgd_gamma: 0.99 #use for krum or multi-krum, ignore
  pgd_project_freq: 5
  
  neurotoxin_topk: 0.03

mr_gamma: 1.0

false_facts_path: ./data/false_facts.json
num_facts: 1
fact_idx: 0

do_train: true

#param file
params_file:
norm_factor: 1000
delta_noise: 0
edited_params_path: 

new_lr_round: -1
layers: [5]

max_norm_list:


norm_factor_list:
rewrite_module_tmp_list: 
grad_steps_list: 

#poison
# repeat: 1
# poison_mode: repeat

eval_mode: strcmp